# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-09 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batch',
            options={'verbose_name_plural': 'Batches'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='batch',
            name='question_file',
            field=models.FileField(default='', upload_to='question_dir'),
            preserve_default=False,
        ),
    ]
