# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 14:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_auto_20160411_1001'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='batch',
            unique_together=set([('name', 'category')]),
        ),
    ]
