# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 22:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0004_auto_20160411_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='duration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='question.Batch'),
        ),
    ]
