# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 19:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('question', '0004_auto_20160411_1428'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField(default=datetime.datetime.now)),
                ('ended_at', models.DateTimeField(default=datetime.datetime.now)),
                ('status', models.PositiveIntegerField(choices=[(0, 0), (1, 1), (2, 2)])),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.Batch')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='exam.Exam'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.Question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='selected',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='question.Option'),
        ),
    ]
