# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, 0), (1, 1), (2, 2)], default=0),
        ),
    ]
