# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-17 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_auto_20160412_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
